config/routes.rb
Rails.application.routes.draw do

root 'homes#index'

 resources :courses do 
    member do
      put "like" =>"courses#upvote"
      put "unlike" =>"courses#downvote"
    end
  end

authenticated :user do
  end


unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
  resources :messages
  end

  resources :courses do 
     resources :comments
   end

  resources :messages
  resources :conversations
  resources :courses
  resources :commenters
  resources :authors
  resources :searches


 devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :homes

  resources :users

  resources :images

  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/commenter.rb
class Commenter < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/controllers/commenters_controller.rb
class CommentersController < ApplicationController
  before_action :set_commenter, only: [:show, :edit, :update, :destroy]

  # GET /commenters
  # GET /commenters.json
  def index
    @commenters = Commenter.all
  end

  # GET /commenters/1
  # GET /commenters/1.json
  def show
  end

  # GET /commenters/new
  def new
    @commenter = Commenter.new
  end

  # GET /commenters/1/edit
  def edit
  end

  # POST /commenters
  # POST /commenters.json
  def create
@commenter = Commenter.new(commenter_params)
@commenter.user = current_user

    respond_to do |format|
      if @commenter.save
        format.html { redirect_to @commenter, notice: 'Commenter was successfully created.' }
        format.json { render :show, status: :created, location: @commenter }
      else
        format.html { render :new }
        format.json { render json: @commenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commenters/1
  # PATCH/PUT /commenters/1.json
  def update
    respond_to do |format|
      if @commenter.update(commenter_params)
        format.html { redirect_to @commenter, notice: 'Commenter was successfully updated.' }
        format.json { render :show, status: :ok, location: @commenter }
      else
        format.html { render :edit }
        format.json { render json: @commenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commenters/1
  # DELETE /commenters/1.json
  def destroy
    @commenter.destroy
    respond_to do |format|
      format.html { redirect_to commenters_url, notice: 'Commenter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commenter
      @commenter = Commenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commenter_params
      params.fetch(:commenter, {})
    end
end

app/helpers/commenters_helper.rb
module CommentersHelper
end

app/views/commenters/_form.html.erb
<%= form_with(model: commenter, local: true) do |form| %>
  <% if commenter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(commenter.errors.count, "error") %> prohibited this commenter from being saved:</h2>

      <ul>
      <% commenter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/commenters/edit.html.erb
<h1>Editing Commenter</h1>

<%= render 'form', commenter: @commenter %>

<%= link_to 'Show', @commenter %> |
<%= link_to 'Back', commenters_path %>

app/views/commenters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commenters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commenters.each do |commenter| %>
      <tr>
        <td><%= link_to 'Show', commenter %></td>
        <td><%= link_to 'Edit', edit_commenter_path(commenter) %></td>
        <td><%= link_to 'Destroy', commenter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commenter', new_commenter_path %>

app/views/commenters/new.html.erb
<h1>New Commenter</h1>

<%= render 'form', commenter: @commenter %>

<%= link_to 'Back', commenters_path %>

app/views/commenters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_commenter_path(@commenter) %> |
<%= link_to 'Back', commenters_path %>