config/routes.rb
Rails.application.routes.draw do

root 'homes#index'

 resources :courses do 
    member do
      put "like" =>"courses#upvote"
      put "unlike" =>"courses#downvote"
    end
  end

authenticated :user do
  end


unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
  resources :messages
  end

  resources :courses do 
     resources :comments
   end

  resources :messages
  resources :conversations
  resources :courses
  resources :commenters
  resources :authors
  resources :searches


 devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :homes

  resources :users

  resources :images

  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	 belongs_to :user
	 has_many :courses
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commenter
	belongs_to :course
end

app/models/commenter.rb
class Commenter < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, ->(user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, ->(sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :author
	has_many :comments

    acts_as_votable
    
	mount_uploader :pdf, PdfUploader 

	def self.search(search)
		if search
			where(["titre LiKE ?","%#{search}%"])
		else
			all
		end
	end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/search.rb
class Search < ApplicationRecord

def courses_search

courses = courses.where(["categorie LIKE ?", categorie]) if categorie.present?
courses = courses.where(["typdedoc LIKE ?", typedoc ]) if typedoc.present?

return courses

end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_one :author
  has_one :commenter
  has_many :conversations, :foreign_key => :sender_id

  acts_as_votable

  attr_accessor :login

validates :username, presence: true, uniqueness: {case_sensitive: false}
validates :formation, presence: true
validates :niveau, presence: true
validates :fac, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   devise :omniauthable, omniauth_providers: [:facebook]

    def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
        where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else
        where(conditions.to_hash).first
    end
end



def self.from_facebook(auth)
  where(facebook_id: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.username = auth.info.name
    user.password = Devise.friendly_token[0,20]
    user.skip_confirmation!
  end
end

 private

  # for demo purposes

  def create_default_conversation
    Conversation.create(sender_id: 1, recipient_id: self.id) unless self.id == 1
  end

mount_uploader :image, ImageUploader

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
 before_action :authenticate_user!, only: [:show]

 def new
    @user = User.new
  end

  def index
      @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
      @conversations = Conversation.involving(current_user).order("created_at DESC")
  end

def create
      @user=User.new(user_params)
      if @user.save
      log_in @user
      redirect_to @user
      else
          render ‘new’
      end
end

  def show
  	@user = User.find(params[:id])
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update 
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
      else 
      render 'edit'
    end
  end

  def private

    def set_user
    end

    def user_params
      params.require(:user).permit(:image, :username, :fac, :formation, :niveau)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/commenters_helper.rb
module CommentersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/views/layouts/_menu.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>

<body>
  <header>

    <div id="mobile-menu-close">
      <i class="fa fa-times" aria-hidden="true"></i>
    </div>

    <ul id="menu" class="shadow">
      <li>
        <%= link_to "Accueil", homes_path %>
      </li>

      <li>
        <%= link_to "Cours", courses_path %>
      </li>

      <li>
        <%= link_to "Messagerie", users_path %>
      </li>

      <li>
        <a href="homes#contact">Contact</a>
      </li>

      <li>            
        <%= link_to "Poster un cours", new_course_path %>
      </li>
    </ul>

    <ul>
      <% if user_signed_in? %>

      <li>
        <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete %>
      </li>

      <li>
        <%= link_to "Profil", users_path %>
      </li>

      <li>
        <%= current_user.email %>
      </li>

      <li>
        <%= link_to "Edit account", edit_user_registration_path %>
      </li>

      <% else %>

      <li>
        <%= link_to "S'inscrire", new_user_registration_path %>
      </li>

      <li>
        <%= link_to "Se connecter", new_user_session_path %>
      </li>

      <li>
        <%= link_to "Se connecter via facebook", user_facebook_omniauth_authorize_path %>
      </li>

      <% end %>
    </ul>

  </header>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freeschool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  </head>

  <body>

  	<p class="alert"><%= alert %></p>
  	<p class="notice"><%= notice %></p>
    <%= yield %>
    <%= render partial: 'layouts/menu' %>


       <ul>
        
  </body>
</html>